<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_QTY_icon_plus</name>
   <tag></tag>
   <elementGuidId>5b123dc3-ac67-4841-9a5f-d3969bfc3256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon_plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-1213']/div/div[2]/form/div/div[2]/div/div/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a9c99bac-c9b5-4a37-bf9f-ab403a92734a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_plus</value>
      <webElementGuid>2e4f9a02-067f-4233-892b-77b16d514f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1213&quot;)/div[@class=&quot;single-product-content&quot;]/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;variations_form cart&quot;]/div[@class=&quot;single_variation_wrap&quot;]/div[@class=&quot;woocommerce-variation-add-to-cart variations_button woocommerce-variation-add-to-cart-enabled&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;noo-quantity-attr&quot;]/button[@class=&quot;qty-increase&quot;]/i[@class=&quot;icon_plus&quot;]</value>
      <webElementGuid>de4e55ad-1ab7-4abb-bb33-d88af85a72e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1213']/div/div[2]/form/div/div[2]/div/div/button[2]/i</value>
      <webElementGuid>71bd747b-5f47-4214-b5a3-7df643af51bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>01965801-24b4-43a8-b7b6-59a03227a51f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
