<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionLargeMediumSmall</name>
   <tag></tag>
   <elementGuidId>6431c38f-2299-4cd4-b02d-4f193160a11c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_size</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_size']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>646bb59f-792b-4ea5-aea1-f8a7a158cba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_size</value>
      <webElementGuid>0f6b5887-e7bc-4934-b488-946991e1ddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>ce86a6a0-b547-4080-9979-7b99ddc0849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>130b306a-5d12-4992-8431-9f6485ff2e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>b3c3325f-1eb1-4895-a801-994b188e7ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionLargeMediumSmall</value>
      <webElementGuid>3005f610-086d-4d85-bac9-95fd26738ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_size&quot;)</value>
      <webElementGuid>132df0b2-4954-42a4-84b5-ce08cf9566c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_size']</value>
      <webElementGuid>ce584ad1-e383-433c-bedd-8bdbeccd6fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1213']/div/div[2]/form/table/tbody/tr[2]/td/select</value>
      <webElementGuid>53144a6d-80b0-431d-8cdd-d65a509e32b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>176cb524-6e5b-4208-b3c8-0ecc4d890eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[2]</value>
      <webElementGuid>10f395e3-61db-4f40-9a33-d8cd8f29742e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[1]</value>
      <webElementGuid>3110b219-00b4-4aa4-be30-b7ad7885bf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::select[1]</value>
      <webElementGuid>807be880-54b4-40c4-8682-3f8aef402543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/select</value>
      <webElementGuid>837e2e39-0da2-4832-98e4-08e4a62ca53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_size' and @name = 'attribute_pa_size' and (text() = 'Choose an optionLargeMediumSmall' or . = 'Choose an optionLargeMediumSmall')]</value>
      <webElementGuid>8009fe8f-f2eb-4041-989e-37a110280547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
